version = 0.1

[default.deploy.parameters]
stack_name = "automation-unfulfilled-orders"
resolve_s3 = true
s3_prefix = "automation-unfulfilled-orders"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ShopifyShop=\"9f5fee.myshopify.com\" ShopifyApiVersion=\"2025-10\" SlackChannelId=\"slack_bot_tests\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"

